import type { Metadata } from "next";
import { Spline_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/general/NavBar/NavBar";
import Divider from "@/components/general/Dividers/Divider";

//const inter = Inter({ subsets: ["latin"] });
const splieSans = Spline_Sans({subsets: ["latin"], weight: ["300", "400", "500", "600", "700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={splieSans.className}>
        <NavBar/>
        <Divider/>
        {children}
        </body>
    </html>
  );
}
